// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	dtos "github.com/yovannylopez/docsy-main/internal/auth/domain/dtos"
	entities "github.com/yovannylopez/docsy-main/internal/auth/domain/entities"

	mock "github.com/stretchr/testify/mock"
)

// AuditRepository is an autogenerated mock type for the AuditRepository type
type AuditRepository struct {
	mock.Mock
}

// GetSessionAuditLogs provides a mock function with given fields: ctx, sessionID, limit, offset
func (_m *AuditRepository) GetSessionAuditLogs(ctx context.Context, sessionID string, limit int, offset int) ([]entities.AuditLog, error) {
	ret := _m.Called(ctx, sessionID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetSessionAuditLogs")
	}

	var r0 []entities.AuditLog
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) ([]entities.AuditLog, error)); ok {
		return rf(ctx, sessionID, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) []entities.AuditLog); ok {
		r0 = rf(ctx, sessionID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.AuditLog)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int) error); ok {
		r1 = rf(ctx, sessionID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserAuditLogs provides a mock function with given fields: ctx, userID, limit, offset
func (_m *AuditRepository) GetUserAuditLogs(ctx context.Context, userID string, limit int, offset int) ([]entities.AuditLog, error) {
	ret := _m.Called(ctx, userID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetUserAuditLogs")
	}

	var r0 []entities.AuditLog
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) ([]entities.AuditLog, error)); ok {
		return rf(ctx, userID, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) []entities.AuditLog); ok {
		r0 = rf(ctx, userID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.AuditLog)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int) error); ok {
		r1 = rf(ctx, userID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx, filters
func (_m *AuditRepository) List(ctx context.Context, filters *dtos.AuditLogFilters) ([]entities.AuditLog, int, error) {
	ret := _m.Called(ctx, filters)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []entities.AuditLog
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, *dtos.AuditLogFilters) ([]entities.AuditLog, int, error)); ok {
		return rf(ctx, filters)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dtos.AuditLogFilters) []entities.AuditLog); ok {
		r0 = rf(ctx, filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.AuditLog)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dtos.AuditLogFilters) int); ok {
		r1 = rf(ctx, filters)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, *dtos.AuditLogFilters) error); ok {
		r2 = rf(ctx, filters)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// LogAction provides a mock function with given fields: ctx, log
func (_m *AuditRepository) LogAction(ctx context.Context, log *entities.AuditLog) error {
	ret := _m.Called(ctx, log)

	if len(ret) == 0 {
		panic("no return value specified for LogAction")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.AuditLog) error); ok {
		r0 = rf(ctx, log)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewAuditRepository creates a new instance of AuditRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuditRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuditRepository {
	mock := &AuditRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
