// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	entities "github.com/yovannylopez/docsy-main/internal/auth/domain/entities"
)

// AuthorizationService is an autogenerated mock type for the AuthorizationService type
type AuthorizationService struct {
	mock.Mock
}

// AssignRoleToUser provides a mock function with given fields: ctx, userID, roleID, assignedBy
func (_m *AuthorizationService) AssignRoleToUser(ctx context.Context, userID string, roleID string, assignedBy string) error {
	ret := _m.Called(ctx, userID, roleID, assignedBy)

	if len(ret) == 0 {
		panic("no return value specified for AssignRoleToUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, userID, roleID, assignedBy)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CheckPermission provides a mock function with given fields: ctx, userID, resource, action
func (_m *AuthorizationService) CheckPermission(ctx context.Context, userID string, resource string, action string) (bool, error) {
	ret := _m.Called(ctx, userID, resource, action)

	if len(ret) == 0 {
		panic("no return value specified for CheckPermission")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (bool, error)); ok {
		return rf(ctx, userID, resource, action)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) bool); ok {
		r0 = rf(ctx, userID, resource, action)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, userID, resource, action)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRolePermissions provides a mock function with given fields: ctx, roleID
func (_m *AuthorizationService) GetRolePermissions(ctx context.Context, roleID string) ([]entities.Permission, error) {
	ret := _m.Called(ctx, roleID)

	if len(ret) == 0 {
		panic("no return value specified for GetRolePermissions")
	}

	var r0 []entities.Permission
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]entities.Permission, error)); ok {
		return rf(ctx, roleID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []entities.Permission); ok {
		r0 = rf(ctx, roleID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.Permission)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, roleID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserPermissions provides a mock function with given fields: ctx, user
func (_m *AuthorizationService) GetUserPermissions(ctx context.Context, user *entities.User) ([]string, error) {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for GetUserPermissions")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.User) ([]string, error)); ok {
		return rf(ctx, user)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entities.User) []string); ok {
		r0 = rf(ctx, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entities.User) error); ok {
		r1 = rf(ctx, user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserPermissionsDetailed provides a mock function with given fields: ctx, userID
func (_m *AuthorizationService) GetUserPermissionsDetailed(ctx context.Context, userID string) ([]entities.Permission, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserPermissionsDetailed")
	}

	var r0 []entities.Permission
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]entities.Permission, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []entities.Permission); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.Permission)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HasPermission provides a mock function with given fields: ctx, user, resource, action
func (_m *AuthorizationService) HasPermission(ctx context.Context, user *entities.User, resource string, action string) bool {
	ret := _m.Called(ctx, user, resource, action)

	if len(ret) == 0 {
		panic("no return value specified for HasPermission")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(context.Context, *entities.User, string, string) bool); ok {
		r0 = rf(ctx, user, resource, action)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// RemoveRoleFromUser provides a mock function with given fields: ctx, userID, roleID
func (_m *AuthorizationService) RemoveRoleFromUser(ctx context.Context, userID string, roleID string) error {
	ret := _m.Called(ctx, userID, roleID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveRoleFromUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, userID, roleID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewAuthorizationService creates a new instance of AuthorizationService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthorizationService(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthorizationService {
	mock := &AuthorizationService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
