// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	entities "github.com/yovannylopez/docsy-main/internal/auth/domain/entities"
)

// AuthenticationService is an autogenerated mock type for the AuthenticationService type
type AuthenticationService struct {
	mock.Mock
}

// Authenticate provides a mock function with given fields: ctx, username, password
func (_m *AuthenticationService) Authenticate(ctx context.Context, username string, password string) (*entities.AuthToken, error) {
	ret := _m.Called(ctx, username, password)

	if len(ret) == 0 {
		panic("no return value specified for Authenticate")
	}

	var r0 *entities.AuthToken
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*entities.AuthToken, error)); ok {
		return rf(ctx, username, password)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *entities.AuthToken); ok {
		r0 = rf(ctx, username, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.AuthToken)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, username, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Login provides a mock function with given fields: ctx, email, password, userAgent, ipAddress
func (_m *AuthenticationService) Login(ctx context.Context, email string, password string, userAgent string, ipAddress string) (*entities.AuthToken, *entities.Session, error) {
	ret := _m.Called(ctx, email, password, userAgent, ipAddress)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *entities.AuthToken
	var r1 *entities.Session
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) (*entities.AuthToken, *entities.Session, error)); ok {
		return rf(ctx, email, password, userAgent, ipAddress)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) *entities.AuthToken); ok {
		r0 = rf(ctx, email, password, userAgent, ipAddress)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.AuthToken)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, string) *entities.Session); ok {
		r1 = rf(ctx, email, password, userAgent, ipAddress)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*entities.Session)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string, string, string) error); ok {
		r2 = rf(ctx, email, password, userAgent, ipAddress)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Logout provides a mock function with given fields: ctx, accessToken, userAgent, ipAddress
func (_m *AuthenticationService) Logout(ctx context.Context, accessToken string, userAgent string, ipAddress string) error {
	ret := _m.Called(ctx, accessToken, userAgent, ipAddress)

	if len(ret) == 0 {
		panic("no return value specified for Logout")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, accessToken, userAgent, ipAddress)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// LogoutAll provides a mock function with given fields: ctx, userID
func (_m *AuthenticationService) LogoutAll(ctx context.Context, userID string) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for LogoutAll")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RefreshToken provides a mock function with given fields: ctx, refreshToken
func (_m *AuthenticationService) RefreshToken(ctx context.Context, refreshToken string) (*entities.AuthToken, error) {
	ret := _m.Called(ctx, refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for RefreshToken")
	}

	var r0 *entities.AuthToken
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entities.AuthToken, error)); ok {
		return rf(ctx, refreshToken)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entities.AuthToken); ok {
		r0 = rf(ctx, refreshToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.AuthToken)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, refreshToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RevokeSession provides a mock function with given fields: ctx, sessionID, reason
func (_m *AuthenticationService) RevokeSession(ctx context.Context, sessionID string, reason string) error {
	ret := _m.Called(ctx, sessionID, reason)

	if len(ret) == 0 {
		panic("no return value specified for RevokeSession")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, sessionID, reason)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ValidateSession provides a mock function with given fields: ctx, sessionID
func (_m *AuthenticationService) ValidateSession(ctx context.Context, sessionID string) (*entities.Session, error) {
	ret := _m.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for ValidateSession")
	}

	var r0 *entities.Session
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entities.Session, error)); ok {
		return rf(ctx, sessionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entities.Session); ok {
		r0 = rf(ctx, sessionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Session)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, sessionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ValidateToken provides a mock function with given fields: ctx, token
func (_m *AuthenticationService) ValidateToken(ctx context.Context, token string) (*entities.User, error) {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for ValidateToken")
	}

	var r0 *entities.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entities.User, error)); ok {
		return rf(ctx, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entities.User); ok {
		r0 = rf(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAuthenticationService creates a new instance of AuthenticationService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthenticationService(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthenticationService {
	mock := &AuthenticationService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
