// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	dtos "github.com/yovannylopez/docsy-main/internal/auth/domain/dtos"
)

// ChangePasswordService is an autogenerated mock type for the ChangePasswordService type
type ChangePasswordService struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, userID, req
func (_m *ChangePasswordService) Execute(ctx context.Context, userID string, req *dtos.ChangePasswordRequest) error {
	ret := _m.Called(ctx, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *dtos.ChangePasswordRequest) error); ok {
		r0 = rf(ctx, userID, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewChangePasswordService creates a new instance of ChangePasswordService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewChangePasswordService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ChangePasswordService {
	mock := &ChangePasswordService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
