// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	dtos "github.com/yovannylopez/docsy-main/internal/auth/domain/dtos"
	entities "github.com/yovannylopez/docsy-main/internal/auth/domain/entities"

	mock "github.com/stretchr/testify/mock"
)

// ListAuditLogsUseCase is an autogenerated mock type for the ListAuditLogsUseCase type
type ListAuditLogsUseCase struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, filters
func (_m *ListAuditLogsUseCase) Execute(ctx context.Context, filters *dtos.AuditLogFilters) ([]entities.AuditLog, int, error) {
	ret := _m.Called(ctx, filters)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 []entities.AuditLog
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, *dtos.AuditLogFilters) ([]entities.AuditLog, int, error)); ok {
		return rf(ctx, filters)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dtos.AuditLogFilters) []entities.AuditLog); ok {
		r0 = rf(ctx, filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.AuditLog)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dtos.AuditLogFilters) int); ok {
		r1 = rf(ctx, filters)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, *dtos.AuditLogFilters) error); ok {
		r2 = rf(ctx, filters)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// NewListAuditLogsUseCase creates a new instance of ListAuditLogsUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewListAuditLogsUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *ListAuditLogsUseCase {
	mock := &ListAuditLogsUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
