// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	dtos "github.com/yovannylopez/docsy-main/internal/auth/domain/dtos"
)

// LoginService is an autogenerated mock type for the LoginService type
type LoginService struct {
	mock.Mock
}

// Login provides a mock function with given fields: ctx, request, userAgent, ipAddress
func (_m *LoginService) Login(ctx context.Context, request *dtos.LoginRequest, userAgent string, ipAddress string) (*dtos.LoginResponse, error) {
	ret := _m.Called(ctx, request, userAgent, ipAddress)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *dtos.LoginResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *dtos.LoginRequest, string, string) (*dtos.LoginResponse, error)); ok {
		return rf(ctx, request, userAgent, ipAddress)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dtos.LoginRequest, string, string) *dtos.LoginResponse); ok {
		r0 = rf(ctx, request, userAgent, ipAddress)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dtos.LoginResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dtos.LoginRequest, string, string) error); ok {
		r1 = rf(ctx, request, userAgent, ipAddress)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewLoginService creates a new instance of LoginService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLoginService(t interface {
	mock.TestingT
	Cleanup(func())
}) *LoginService {
	mock := &LoginService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
