// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	dtos "github.com/yovannylopez/docsy-main/internal/auth/domain/dtos"
)

// MFAVerifyService is an autogenerated mock type for the MFAVerifyService type
type MFAVerifyService struct {
	mock.Mock
}

// Verify provides a mock function with given fields: ctx, req
func (_m *MFAVerifyService) Verify(ctx context.Context, req *dtos.MFAVerifyRequest) (*dtos.LoginResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Verify")
	}

	var r0 *dtos.LoginResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *dtos.MFAVerifyRequest) (*dtos.LoginResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dtos.MFAVerifyRequest) *dtos.LoginResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dtos.LoginResponse)
		}
	}
	if rf, ok := ret.Get(1).(func(context.Context, *dtos.MFAVerifyRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// NewMFAVerifyService creates a new instance of MFAVerifyService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMFAVerifyService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MFAVerifyService {
	mock := &MFAVerifyService{}
	mock.Mock.Test(t)
	t.Cleanup(func() { mock.AssertExpectations(t) })
	return mock
}
