// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MFASecretEncryptor is an autogenerated mock type for the MFASecretEncryptor type
type MFASecretEncryptor struct {
	mock.Mock
}

// Encrypt provides a mock function with given fields: ctx, plainSecret
func (_m *MFASecretEncryptor) Encrypt(ctx context.Context, plainSecret string) (string, error) {
	ret := _m.Called(ctx, plainSecret)

	if len(ret) == 0 {
		panic("no return value specified for Encrypt")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, plainSecret)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, plainSecret)
	} else {
		r0 = ret.Get(0).(string)
	}
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, plainSecret)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Decrypt provides a mock function with given fields: ctx, encrypted
func (_m *MFASecretEncryptor) Decrypt(ctx context.Context, encrypted string) (string, error) {
	ret := _m.Called(ctx, encrypted)

	if len(ret) == 0 {
		panic("no return value specified for Decrypt")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, encrypted)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, encrypted)
	} else {
		r0 = ret.Get(0).(string)
	}
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, encrypted)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// NewMFASecretEncryptor creates a new instance of MFASecretEncryptor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMFASecretEncryptor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MFASecretEncryptor {
	mock := &MFASecretEncryptor{}
	mock.Mock.Test(t)
	t.Cleanup(func() { mock.AssertExpectations(t) })
	return mock
}
