// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	dtos "github.com/yovannylopez/docsy-main/internal/auth/domain/dtos"
)

// MFASetupService is an autogenerated mock type for the MFASetupService type
type MFASetupService struct {
	mock.Mock
}

// Setup provides a mock function with given fields: ctx, userID
func (_m *MFASetupService) Setup(ctx context.Context, userID string) (*dtos.MFASetupResponse, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for Setup")
	}

	var r0 *dtos.MFASetupResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*dtos.MFASetupResponse, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *dtos.MFASetupResponse); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dtos.MFASetupResponse)
		}
	}
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// NewMFASetupService creates a new instance of MFASetupService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMFASetupService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MFASetupService {
	mock := &MFASetupService{}
	mock.Mock.Test(t)
	t.Cleanup(func() { mock.AssertExpectations(t) })
	return mock
}
