// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	dtos "github.com/yovannylopez/docsy-main/internal/auth/domain/dtos"
)

// MFADisableService is an autogenerated mock type for the MFADisableService type
type MFADisableService struct {
	mock.Mock
}

// Disable provides a mock function with given fields: ctx, userID, req
func (_m *MFADisableService) Disable(ctx context.Context, userID string, req *dtos.MFADisableRequest) error {
	ret := _m.Called(ctx, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for Disable")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *dtos.MFADisableRequest) error); ok {
		r0 = rf(ctx, userID, req)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// NewMFADisableService creates a new instance of MFADisableService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMFADisableService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MFADisableService {
	mock := &MFADisableService{}
	mock.Mock.Test(t)
	t.Cleanup(func() { mock.AssertExpectations(t) })
	return mock
}
