// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	dtos "github.com/yovannylopez/docsy-main/internal/auth/domain/dtos"
)

// MFAConfirmService is an autogenerated mock type for the MFAConfirmService type
type MFAConfirmService struct {
	mock.Mock
}

// Confirm provides a mock function with given fields: ctx, userID, req
func (_m *MFAConfirmService) Confirm(ctx context.Context, userID string, req *dtos.MFAConfirmRequest) error {
	ret := _m.Called(ctx, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for Confirm")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *dtos.MFAConfirmRequest) error); ok {
		r0 = rf(ctx, userID, req)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// NewMFAConfirmService creates a new instance of MFAConfirmService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMFAConfirmService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MFAConfirmService {
	mock := &MFAConfirmService{}
	mock.Mock.Test(t)
	t.Cleanup(func() { mock.AssertExpectations(t) })
	return mock
}
