// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	entities "github.com/yovannylopez/docsy-main/internal/auth/domain/entities"
)

// PasswordHistoryRepository is an autogenerated mock type for the PasswordHistoryRepository type
type PasswordHistoryRepository struct {
	mock.Mock
}

// CheckPasswordInHistory provides a mock function with given fields: ctx, userID, passwordHash
func (_m *PasswordHistoryRepository) CheckPasswordInHistory(ctx context.Context, userID string, passwordHash string) (bool, error) {
	ret := _m.Called(ctx, userID, passwordHash)

	if len(ret) == 0 {
		panic("no return value specified for CheckPasswordInHistory")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return rf(ctx, userID, passwordHash)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = rf(ctx, userID, passwordHash)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userID, passwordHash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CleanOldPasswordHistory provides a mock function with given fields: ctx, userID, keepCount
func (_m *PasswordHistoryRepository) CleanOldPasswordHistory(ctx context.Context, userID string, keepCount int) error {
	ret := _m.Called(ctx, userID, keepCount)

	if len(ret) == 0 {
		panic("no return value specified for CleanOldPasswordHistory")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int) error); ok {
		r0 = rf(ctx, userID, keepCount)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Create provides a mock function with given fields: ctx, passwordHistory
func (_m *PasswordHistoryRepository) Create(ctx context.Context, passwordHistory *entities.PasswordHistory) error {
	ret := _m.Called(ctx, passwordHistory)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.PasswordHistory) error); ok {
		r0 = rf(ctx, passwordHistory)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetUserPasswordHistory provides a mock function with given fields: ctx, userID, limit
func (_m *PasswordHistoryRepository) GetUserPasswordHistory(ctx context.Context, userID string, limit int) ([]entities.PasswordHistory, error) {
	ret := _m.Called(ctx, userID, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetUserPasswordHistory")
	}

	var r0 []entities.PasswordHistory
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int) ([]entities.PasswordHistory, error)); ok {
		return rf(ctx, userID, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int) []entities.PasswordHistory); ok {
		r0 = rf(ctx, userID, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.PasswordHistory)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = rf(ctx, userID, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPasswordHistoryRepository creates a new instance of PasswordHistoryRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPasswordHistoryRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *PasswordHistoryRepository {
	mock := &PasswordHistoryRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
