// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	entities "github.com/yovannylopez/docsy-main/internal/auth/domain/entities"
)

// SessionRepository is an autogenerated mock type for the SessionRepository type
type SessionRepository struct {
	mock.Mock
}

// CleanupExpiredSessions provides a mock function with given fields: ctx
func (_m *SessionRepository) CleanupExpiredSessions(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CleanupExpiredSessions")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Create provides a mock function with given fields: ctx, session
func (_m *SessionRepository) Create(ctx context.Context, session *entities.Session) error {
	ret := _m.Called(ctx, session)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.Session) error); ok {
		r0 = rf(ctx, session)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindByID provides a mock function with given fields: ctx, sessionID
func (_m *SessionRepository) FindByID(ctx context.Context, sessionID string) (*entities.Session, error) {
	ret := _m.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *entities.Session
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entities.Session, error)); ok {
		return rf(ctx, sessionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entities.Session); ok {
		r0 = rf(ctx, sessionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Session)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, sessionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByRefreshToken provides a mock function with given fields: ctx, refreshTokenHash
func (_m *SessionRepository) FindByRefreshToken(ctx context.Context, refreshTokenHash string) (*entities.Session, error) {
	ret := _m.Called(ctx, refreshTokenHash)

	if len(ret) == 0 {
		panic("no return value specified for FindByRefreshToken")
	}

	var r0 *entities.Session
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entities.Session, error)); ok {
		return rf(ctx, refreshTokenHash)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entities.Session); ok {
		r0 = rf(ctx, refreshTokenHash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Session)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, refreshTokenHash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByUserID provides a mock function with given fields: ctx, userID
func (_m *SessionRepository) FindByUserID(ctx context.Context, userID string) ([]entities.Session, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for FindByUserID")
	}

	var r0 []entities.Session
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]entities.Session, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []entities.Session); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.Session)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RevokeAllUserSessions provides a mock function with given fields: ctx, userID, reason
func (_m *SessionRepository) RevokeAllUserSessions(ctx context.Context, userID string, reason string) error {
	ret := _m.Called(ctx, userID, reason)

	if len(ret) == 0 {
		panic("no return value specified for RevokeAllUserSessions")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, userID, reason)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RevokeSession provides a mock function with given fields: ctx, sessionID, reason
func (_m *SessionRepository) RevokeSession(ctx context.Context, sessionID string, reason string) error {
	ret := _m.Called(ctx, sessionID, reason)

	if len(ret) == 0 {
		panic("no return value specified for RevokeSession")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, sessionID, reason)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: ctx, session
func (_m *SessionRepository) Update(ctx context.Context, session *entities.Session) error {
	ret := _m.Called(ctx, session)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.Session) error); ok {
		r0 = rf(ctx, session)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateLastUsed provides a mock function with given fields: ctx, sessionID
func (_m *SessionRepository) UpdateLastUsed(ctx context.Context, sessionID string) error {
	ret := _m.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for UpdateLastUsed")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, sessionID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewSessionRepository creates a new instance of SessionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSessionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *SessionRepository {
	mock := &SessionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
