// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	entities "github.com/yovannylopez/docsy-main/internal/auth/domain/entities"
)

// SystemConfigRepository is an autogenerated mock type for the SystemConfigRepository type
type SystemConfigRepository struct {
	mock.Mock
}

// DeleteConfig provides a mock function with given fields: ctx, key
func (_m *SystemConfigRepository) DeleteConfig(ctx context.Context, key string) error {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for DeleteConfig")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, key)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAllConfig provides a mock function with given fields: ctx
func (_m *SystemConfigRepository) GetAllConfig(ctx context.Context) ([]entities.SystemConfig, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllConfig")
	}

	var r0 []entities.SystemConfig
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]entities.SystemConfig, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []entities.SystemConfig); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.SystemConfig)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetConfig provides a mock function with given fields: ctx, key
func (_m *SystemConfigRepository) GetConfig(ctx context.Context, key string) (*entities.SystemConfig, error) {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for GetConfig")
	}

	var r0 *entities.SystemConfig
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entities.SystemConfig, error)); ok {
		return rf(ctx, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entities.SystemConfig); ok {
		r0 = rf(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.SystemConfig)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetConfig provides a mock function with given fields: ctx, config
func (_m *SystemConfigRepository) SetConfig(ctx context.Context, config *entities.SystemConfig) error {
	ret := _m.Called(ctx, config)

	if len(ret) == 0 {
		panic("no return value specified for SetConfig")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.SystemConfig) error); ok {
		r0 = rf(ctx, config)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewSystemConfigRepository creates a new instance of SystemConfigRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSystemConfigRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *SystemConfigRepository {
	mock := &SystemConfigRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
