// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	entities "github.com/yovannylopez/docsy-main/internal/auth/domain/entities"
)

// TokenGenerator is an autogenerated mock type for the TokenGenerator type
type TokenGenerator struct {
	mock.Mock
}

// GenerateToken provides a mock function with given fields: user, sessionID
func (_m *TokenGenerator) GenerateToken(user *entities.User, sessionID string) (*entities.AuthToken, error) {
	ret := _m.Called(user, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for GenerateToken")
	}

	var r0 *entities.AuthToken
	var r1 error
	if rf, ok := ret.Get(0).(func(*entities.User, string) (*entities.AuthToken, error)); ok {
		return rf(user, sessionID)
	}
	if rf, ok := ret.Get(0).(func(*entities.User, string) *entities.AuthToken); ok {
		r0 = rf(user, sessionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.AuthToken)
		}
	}

	if rf, ok := ret.Get(1).(func(*entities.User, string) error); ok {
		r1 = rf(user, sessionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ParseRefreshToken provides a mock function with given fields: refreshToken
func (_m *TokenGenerator) ParseRefreshToken(refreshToken string) (string, string, error) {
	ret := _m.Called(refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for ParseRefreshToken")
	}

	var r0 string
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(string) (string, string, error)); ok {
		return rf(refreshToken)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(refreshToken)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) string); ok {
		r1 = rf(refreshToken)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(string) error); ok {
		r2 = rf(refreshToken)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ValidateToken provides a mock function with given fields: tokenString
func (_m *TokenGenerator) ValidateToken(tokenString string) (map[string]interface{}, error) {
	ret := _m.Called(tokenString)

	if len(ret) == 0 {
		panic("no return value specified for ValidateToken")
	}

	var r0 map[string]interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (map[string]interface{}, error)); ok {
		return rf(tokenString)
	}
	if rf, ok := ret.Get(0).(func(string) map[string]interface{}); ok {
		r0 = rf(tokenString)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(tokenString)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTokenGenerator creates a new instance of TokenGenerator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTokenGenerator(t interface {
	mock.TestingT
	Cleanup(func())
}) *TokenGenerator {
	mock := &TokenGenerator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
