// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// TOTPProvider is an autogenerated mock type for the TOTPProvider type
type TOTPProvider struct {
	mock.Mock
}

// GenerateSecret provides a mock function with given fields: ctx, issuer, accountName
func (_m *TOTPProvider) GenerateSecret(ctx context.Context, issuer string, accountName string) (string, string, error) {
	ret := _m.Called(ctx, issuer, accountName)

	if len(ret) == 0 {
		panic("no return value specified for GenerateSecret")
	}

	var r0 string
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (string, string, error)); ok {
		return rf(ctx, issuer, accountName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, issuer, accountName)
	} else {
		r0 = ret.Get(0).(string)
	}
	if rf, ok := ret.Get(1).(func(context.Context, string, string) string); ok {
		r1 = rf(ctx, issuer, accountName)
	} else {
		r1 = ret.Get(1).(string)
	}
	if rf, ok := ret.Get(2).(func(context.Context, string, string) error); ok {
		r2 = rf(ctx, issuer, accountName)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// ValidateCode provides a mock function with given fields: ctx, secret, code
func (_m *TOTPProvider) ValidateCode(ctx context.Context, secret string, code string) (bool, error) {
	ret := _m.Called(ctx, secret, code)

	if len(ret) == 0 {
		panic("no return value specified for ValidateCode")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return rf(ctx, secret, code)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = rf(ctx, secret, code)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, secret, code)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// NewTOTPProvider creates a new instance of TOTPProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewTOTPProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *TOTPProvider {
	mock := &TOTPProvider{}
	mock.Mock.Test(t)
	t.Cleanup(func() { mock.AssertExpectations(t) })
	return mock
}
