// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	entities "github.com/yovannylopez/docsy-main/internal/auth/domain/entities"

	ports "github.com/yovannylopez/docsy-main/internal/auth/domain/ports"

	time "time"
)

// UserRepository is an autogenerated mock type for the UserRepository type
type UserRepository struct {
	mock.Mock
}

// CountSearchUsers provides a mock function with given fields: ctx, query, activo
func (_m *UserRepository) CountSearchUsers(ctx context.Context, query string, activo *bool) (int, error) {
	ret := _m.Called(ctx, query, activo)

	if len(ret) == 0 {
		panic("no return value specified for CountSearchUsers")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *bool) (int, error)); ok {
		return rf(ctx, query, activo)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *bool) int); ok {
		r0 = rf(ctx, query, activo)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *bool) error); ok {
		r1 = rf(ctx, query, activo)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Create provides a mock function with given fields: ctx, user
func (_m *UserRepository) Create(ctx context.Context, user *entities.User) error {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.User) error); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DisableMFA provides a mock function with given fields: ctx, userID
func (_m *UserRepository) DisableMFA(ctx context.Context, userID string) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for DisableMFA")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// EnableMFA provides a mock function with given fields: ctx, userID, secret
func (_m *UserRepository) EnableMFA(ctx context.Context, userID string, secret string) error {
	ret := _m.Called(ctx, userID, secret)

	if len(ret) == 0 {
		panic("no return value specified for EnableMFA")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, userID, secret)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindByEmail provides a mock function with given fields: ctx, email
func (_m *UserRepository) FindByEmail(ctx context.Context, email string) (*entities.User, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for FindByEmail")
	}

	var r0 *entities.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entities.User, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entities.User); ok {
		r0 = rf(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByID provides a mock function with given fields: ctx, userID
func (_m *UserRepository) FindByID(ctx context.Context, userID string) (*entities.User, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *entities.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entities.User, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entities.User); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByUsername provides a mock function with given fields: ctx, username
func (_m *UserRepository) FindByUsername(ctx context.Context, username string) (*entities.User, error) {
	ret := _m.Called(ctx, username)

	if len(ret) == 0 {
		panic("no return value specified for FindByUsername")
	}

	var r0 *entities.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entities.User, error)); ok {
		return rf(ctx, username)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entities.User); ok {
		r0 = rf(ctx, username)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, username)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllUsers provides a mock function with given fields: ctx, limit, offset
func (_m *UserRepository) GetAllUsers(ctx context.Context, limit int, offset int) ([]entities.User, error) {
	ret := _m.Called(ctx, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetAllUsers")
	}

	var r0 []entities.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) ([]entities.User, error)); ok {
		return rf(ctx, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) []entities.User); ok {
		r0 = rf(ctx, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRoleByName provides a mock function with given fields: ctx, roleName
func (_m *UserRepository) GetRoleByName(ctx context.Context, roleName string) (*entities.Role, error) {
	ret := _m.Called(ctx, roleName)

	if len(ret) == 0 {
		panic("no return value specified for GetRoleByName")
	}

	var r0 *entities.Role
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entities.Role, error)); ok {
		return rf(ctx, roleName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entities.Role); ok {
		r0 = rf(ctx, roleName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Role)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, roleName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTotalUsersCount provides a mock function with given fields: ctx
func (_m *UserRepository) GetTotalUsersCount(ctx context.Context) (int, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetTotalUsersCount")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (int, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) int); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IncrementFailedLoginAttempts provides a mock function with given fields: ctx, userID
func (_m *UserRepository) IncrementFailedLoginAttempts(ctx context.Context, userID string) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for IncrementFailedLoginAttempts")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// LockUserAccount provides a mock function with given fields: ctx, userID, until
func (_m *UserRepository) LockUserAccount(ctx context.Context, userID string, until *time.Time) error {
	ret := _m.Called(ctx, userID, until)

	if len(ret) == 0 {
		panic("no return value specified for LockUserAccount")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *time.Time) error); ok {
		r0 = rf(ctx, userID, until)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RecordFailedPasswordAttempt provides a mock function with given fields: ctx, userID, maxAttempts, lockDuration
func (_m *UserRepository) RecordFailedPasswordAttempt(ctx context.Context, userID string, maxAttempts int, lockDuration time.Duration) (ports.FailedPasswordAttemptResult, error) {
	ret := _m.Called(ctx, userID, maxAttempts, lockDuration)

	if len(ret) == 0 {
		panic("no return value specified for RecordFailedPasswordAttempt")
	}

	var r0 ports.FailedPasswordAttemptResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, time.Duration) (ports.FailedPasswordAttemptResult, error)); ok {
		return rf(ctx, userID, maxAttempts, lockDuration)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, time.Duration) ports.FailedPasswordAttemptResult); ok {
		r0 = rf(ctx, userID, maxAttempts, lockDuration)
	} else {
		r0 = ret.Get(0).(ports.FailedPasswordAttemptResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, time.Duration) error); ok {
		r1 = rf(ctx, userID, maxAttempts, lockDuration)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ResetFailedLoginAttempts provides a mock function with given fields: ctx, userID
func (_m *UserRepository) ResetFailedLoginAttempts(ctx context.Context, userID string) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ResetFailedLoginAttempts")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SearchUsers provides a mock function with given fields: ctx, query, activo, limit, offset
func (_m *UserRepository) SearchUsers(ctx context.Context, query string, activo *bool, limit int, offset int) ([]entities.User, error) {
	ret := _m.Called(ctx, query, activo, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for SearchUsers")
	}

	var r0 []entities.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *bool, int, int) ([]entities.User, error)); ok {
		return rf(ctx, query, activo, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *bool, int, int) []entities.User); ok {
		r0 = rf(ctx, query, activo, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *bool, int, int) error); ok {
		r1 = rf(ctx, query, activo, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetMustChangePassword provides a mock function with given fields: ctx, userID, mustChange
func (_m *UserRepository) SetMustChangePassword(ctx context.Context, userID string, mustChange bool) error {
	ret := _m.Called(ctx, userID, mustChange)

	if len(ret) == 0 {
		panic("no return value specified for SetMustChangePassword")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, bool) error); ok {
		r0 = rf(ctx, userID, mustChange)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UnlockUserAccount provides a mock function with given fields: ctx, userID
func (_m *UserRepository) UnlockUserAccount(ctx context.Context, userID string) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for UnlockUserAccount")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: ctx, user
func (_m *UserRepository) Update(ctx context.Context, user *entities.User) error {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.User) error); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateLastLogin provides a mock function with given fields: ctx, userID
func (_m *UserRepository) UpdateLastLogin(ctx context.Context, userID string) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for UpdateLastLogin")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateMFASecret provides a mock function with given fields: ctx, userID, encryptedSecret
func (_m *UserRepository) UpdateMFASecret(ctx context.Context, userID string, encryptedSecret string) error {
	ret := _m.Called(ctx, userID, encryptedSecret)

	if len(ret) == 0 {
		panic("no return value specified for UpdateMFASecret")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, userID, encryptedSecret)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdatePassword provides a mock function with given fields: ctx, userID, passwordHash
func (_m *UserRepository) UpdatePassword(ctx context.Context, userID string, passwordHash string) error {
	ret := _m.Called(ctx, userID, passwordHash)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePassword")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, userID, passwordHash)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// VerifyUser provides a mock function with given fields: ctx, userID
func (_m *UserRepository) VerifyUser(ctx context.Context, userID string) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for VerifyUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewUserRepository creates a new instance of UserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserRepository {
	mock := &UserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
