// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	entities "github.com/yovannylopez/docsy-main/internal/auth/domain/entities"
)

// VerificationTokenRepository is an autogenerated mock type for the VerificationTokenRepository type
type VerificationTokenRepository struct {
	mock.Mock
}

// CreateToken provides a mock function with given fields: ctx, token
func (_m *VerificationTokenRepository) CreateToken(ctx context.Context, token *entities.VerificationToken) error {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for CreateToken")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.VerificationToken) error); ok {
		r0 = rf(ctx, token)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// FindTokenByHash provides a mock function with given fields: ctx, tokenHash
func (_m *VerificationTokenRepository) FindTokenByHash(ctx context.Context, tokenHash string) (*entities.VerificationToken, error) {
	ret := _m.Called(ctx, tokenHash)

	if len(ret) == 0 {
		panic("no return value specified for FindTokenByHash")
	}

	var r0 *entities.VerificationToken
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entities.VerificationToken, error)); ok {
		return rf(ctx, tokenHash)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entities.VerificationToken); ok {
		r0 = rf(ctx, tokenHash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.VerificationToken)
		}
	}
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, tokenHash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MarkTokenAsUsed provides a mock function with given fields: ctx, tokenID
func (_m *VerificationTokenRepository) MarkTokenAsUsed(ctx context.Context, tokenID string) error {
	ret := _m.Called(ctx, tokenID)

	if len(ret) == 0 {
		panic("no return value specified for MarkTokenAsUsed")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, tokenID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// CleanExpiredTokens provides a mock function with given fields: ctx
func (_m *VerificationTokenRepository) CleanExpiredTokens(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CleanExpiredTokens")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// GetUserTokens provides a mock function with given fields: ctx, userID, tokenType
func (_m *VerificationTokenRepository) GetUserTokens(ctx context.Context, userID string, tokenType string) ([]entities.VerificationToken, error) {
	ret := _m.Called(ctx, userID, tokenType)

	if len(ret) == 0 {
		panic("no return value specified for GetUserTokens")
	}

	var r0 []entities.VerificationToken
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) ([]entities.VerificationToken, error)); ok {
		return rf(ctx, userID, tokenType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []entities.VerificationToken); ok {
		r0 = rf(ctx, userID, tokenType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.VerificationToken)
		}
	}
	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userID, tokenType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// NewVerificationTokenRepository creates a new instance of VerificationTokenRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewVerificationTokenRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *VerificationTokenRepository {
	mock := &VerificationTokenRepository{}
	mock.Mock.Test(t)
	t.Cleanup(func() { mock.AssertExpectations(t) })
	return mock
}
