// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// AppConfig is an autogenerated mock type for the AppConfig type
type AppConfig struct {
	mock.Mock
}

type AppConfig_Expecter struct {
	mock *mock.Mock
}

func (_m *AppConfig) EXPECT() *AppConfig_Expecter {
	return &AppConfig_Expecter{mock: &_m.Mock}
}

// Validate provides a mock function with no fields
func (_m *AppConfig) Validate() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Validate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AppConfig_Validate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Validate'
type AppConfig_Validate_Call struct {
	*mock.Call
}

// Validate is a helper method to define mock.On call
func (_e *AppConfig_Expecter) Validate() *AppConfig_Validate_Call {
	return &AppConfig_Validate_Call{Call: _e.mock.On("Validate")}
}

func (_c *AppConfig_Validate_Call) Run(run func()) *AppConfig_Validate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *AppConfig_Validate_Call) Return(_a0 error) *AppConfig_Validate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AppConfig_Validate_Call) RunAndReturn(run func() error) *AppConfig_Validate_Call {
	_c.Call.Return(run)
	return _c
}

// NewAppConfig creates a new instance of AppConfig. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAppConfig(t interface {
	mock.TestingT
	Cleanup(func())
}) *AppConfig {
	mock := &AppConfig{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
